UdemyIdentity/Controllers/PanelController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using UdemyIdentity.Context;
using UdemyIdentity.Models;

namespace UdemyIdentity.Controllers
{
    [Authorize]
    public class PanelController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;
        public PanelController(UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public async Task<IActionResult> Index()
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);

            return View(user);
        }

        public async Task<IActionResult> UpdateUser()
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);

            UserUpdateViewModel model = new UserUpdateViewModel
            {
                Email = user.Email,
                FirstName = user.FirstName,
                LastName = user.LastName,
                PhoneNumber = user.PhoneNumber,
                PictureUrl = user.PictureUrl
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateUser(UserUpdateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByNameAsync(User.Identity.Name);

                if (model.PictureFile != null)
                {
                    var currentDirectory = Directory.GetCurrentDirectory();
                    var fileExtension = Path.GetExtension(model.PictureFile.FileName);
                    var pictureFileName = Guid.NewGuid() + fileExtension;
                    var filePath = currentDirectory + "/wwwroot/img/" + pictureFileName; 

                    using var fileStream = new FileStream(filePath, FileMode.Create);

                    await model.PictureFile.CopyToAsync(fileStream);
                    user.PictureUrl = pictureFileName;
                }

                user.FirstName = model.FirstName;
                user.LastName = model.LastName;
                user.Email = model.Email;
                user.PhoneNumber = model.PhoneNumber;

                var result = await _userManager.UpdateAsync(user);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }
            }

            return View(model);
        }

        [AllowAnonymous] // herkese açık
        public IActionResult Index2()
        {
            return View();
        }

        public async Task<IActionResult> LogOut()
        {
            await _signInManager.SignOutAsync();

            return RedirectToAction("Index", "Home");
        }
    }
}

UdemyIdentity/Views/Panel/Index.cshtml
@model AppUser
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Profil Bilgilerim</h4>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-9">
            <table class="table table-hover">
                <tr>
                    <th>Kullanıcı Adı</th>
                    <td>@Model.FirstName</td>
                </tr>
                <tr>
                    <th>Kullanıcı Soyadı</th>
                    <td>@Model.LastName</td>
                </tr>
                <tr>
                    <th>Email</th>
                    <td>@Model.Email</td>
                </tr>
                <tr>
                    <th>Telefon</th>
                    <td>@Model.PhoneNumber</td>
                </tr>
            </table>
        </div>
        <div class="col-md-3">
            <img src="~/img/@Model.PictureUrl" alt="@(Model.FirstName + " " + Model.LastName)" class="img-fluid img-thumbnail" />
        </div>
    </div>
</div>

UdemyIdentity/Views/Panel/UpdateUser.cshtml
@model UserUpdateViewModel
@{
    ViewData["Title"] = "Bilgilerimi Güncelle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Bilgilerimi Güncelle</h4>

<div class="container-fluid">
    <form asp-action="UpdateUser" asp-controller="Panel" method="post" class="w-100 shadow p-3" enctype="multipart/form-data">

        <div class="form-group">
            <label asp-for="FirstName"></label>
            <input asp-for="FirstName" class="form-control" />
            <span class="text-danger" asp-validation-for="FirstName"></span>
        </div>

        <div class="form-group">
            <label asp-for="LastName"></label>
            <input asp-for="LastName" class="form-control" />
            <span class="text-danger" asp-validation-for="LastName"></span>
        </div>

        <div class="form-group">
            <label asp-for="Email"></label>
            <input asp-for="Email" class="form-control" />
            <span class="text-danger" asp-validation-for="Email"></span>
        </div>

        <div class="form-group">
            <label asp-for="PhoneNumber"></label>
            <input asp-for="PhoneNumber" class="form-control" />
            <span class="text-danger" asp-validation-for="PhoneNumber"></span>
        </div>

        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    <label asp-for="PictureFile"></label>
                    <input asp-for="PictureFile" class="form-control" />
                    <span class="text-danger" asp-validation-for="PictureFile"></span>
                </div>
            </div>
            <div class="col-md-4">
                <label asp-for="PictureUrl"></label>
                <br />
                <img src="~/img/@Model.PictureUrl" alt="@Model.PictureUrl" class="img-thumbnail" />
            </div>
        </div>

        <div class="text-danger" asp-validation-summary="ModelOnly"></div>

        <input type="submit" class="btn btn-outline-success btn-sm" value="Güncelle" />
    </form>
</div>